// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwdfWpnmIh9JxqZVzhPg7XKDENyDYF2_A',
    appId: '1:187490305574:ios:4df65760385f860337c8e7',
    messagingSenderId: '187490305574',
    projectId: 'instantgram-clone-course-zak',
    storageBucket: 'instantgram-clone-course-zak.appspot.com',
    iosBundleId: 'com.example.instantgramCloneCourse',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1mQH9LBB5cQ2dWWeniMrQcD0-zbUXQCc',
    appId: '1:187490305574:android:ee54a27b351386be37c8e7',
    messagingSenderId: '187490305574',
    projectId: 'instantgram-clone-course-zak',
    storageBucket: 'instantgram-clone-course-zak.appspot.com',
  );
}
